### PR TITLE
Add tests for prefer english names and remove support for media folders

### PR DESCRIPTION
**Pull request by jmathai**
I like the option of media folders but would prefer to include it as part of the directory configuration so you can add a `%media_type` anywhere in the folder name.

### CODE REVIEW

**Comment by jmathai** [comment]
@DZamataev once you merge this I can merge your PR.

**Comment by DZamataev** [comment]
Ok great!

**Comment by jmathai** [comment]
Squashed and merged. You may want to delete your fork and refork since the squash changes commit history that's different from what you have in master.

To avoid this in the future you can submit a pull request from a non-master branch in your fork :)

Thanks for the PR!

**Comment by DZamataev** [comment]
ok great, but i may loose the implementation of separating media folders. I use it currently to sort out my pretty large library.

**Comment by DZamataev** [comment]
And I also implemented moving instead of copy-then-trashing source files while importing the library.

**Comment by DZamataev** [comment]
So putting it into separate branch for future PRs is what i'm gonna do.

**Pull request merged**
